### login test
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### getUserInfo test
GET {{baseUrl}}/user
Content-Type: application/json

### logout test
POST {{baseUrl}}/user/logout
Content-Type: application/json

### getAllCategory test
GET {{baseUrl}}/categories
Content-Type: application/json

### getPageOfProduct test1: no params
GET {{baseUrl}}/pages
Content-Type: application/json

### getPageOfProduct test2: pageNum, pageSize
GET {{baseUrl}}/pages?pageNum=1&pageSize=2
Content-Type: application/json

### getPageOfProduct test3: category, pageSize, pageNum
GET {{baseUrl}}/pages/100002?pageNum=1&pageSize=2
Content-Type: application/json

### getPageOfProduct test4: category
GET {{baseUrl}}/pages/100002
Content-Type: application/json

### getProductDetail test
GET {{baseUrl}}/product/26
Content-Type: application/json

###
